name: feeltong-running-dev

services:
  running-front:
    container_name: running-front-dev
    build:
      context: ../feeltong-running-web
      dockerfile: Dockerfile
    restart: always
    environment:
      APP_BACK_URL: ${APP_BACK_URL}
    depends_on:
      - running-back
    networks:
      - running

  running-back:
    container_name: running-back-dev
    image: ${REGISTRY}/feeltong-running-back:${BACK_TAG}
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_PATH: ${DB_PATH}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_JWKS_URL: ${SUPABASE_JWKS_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      CORS_WHITELIST: ${CORS_WHITELIST}
    depends_on:
      - running-mongodb
    networks:
      - running

  running-mongodb:
    container_name: running-mongodb-dev
    image: mongo:7
    restart: always
    volumes:
      - running_mongodb_data:/data/db:rw
    networks:
      - running

  running-proxy:
    container_name: running-proxy-dev
    image: nginx:1.27-alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - running-front
      - running-back
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d:ro
    networks:
      - running

volumes:
  running_mongodb_data:

networks:
  running:
